version: "3.5"

services:

  feed-composer:
    container_name: dev_pledge_feed_composer
    image: twosee/swoole-coroutine
    working_dir: /app/src
    volumes:
      - .:/app/src
    command: composer install

  feed:
    container_name: dev_pledge_feed
    image: twosee/swoole-coroutine
    env_file:
    #create a .sentry-env use .sentry-example-env as template...
      - .sentry-env
      - .app-dev-env
    volumes:
      - .:/app/src:cached
    expose:
      - 9501
    networks:
      - default
      - sentry_network
      - cache_network
    command: php /app/src/feed.php
    restart: always

networks:
  default:
    name: devpledge_feed

  sentry_network:
    external:
      name: global_sentry

  cache_network:
    external:
      name: devpledge_cache


